services:
  db:
    image: postgres:15-alpine
    container_name: civa-postgres-db
    environment:
      POSTGRES_USER: salim_user
      POSTGRES_PASSWORD: salim_password
      POSTGRES_DB: civa_bus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: